### ISSUE TITLE
slow throughput in 0.0.4

### ISSUE THREAD

**Issue by VerisZG** [Keranik/MassiveStorageMod#4]
Hi, I reimported this 0.0.4 release into my savegame, but the throughput of incoming belts went down. Now storages can input something like 1,5 tier 2 belts. Connecting more belts doesn't help in any way. 0.0.3 was ok though.

0.0.3 almost immediately trasfered items between chained storages, now it is totally slow.

**Comment by VerisZG** [comment]
https://github.com/Keranik/MassiveStorageMod/assets/1569499/fafe601f-2b91-4f8f-850e-a82e7469f2bc
As you can see on the vid, it barely takes 2 belts and even pauses during input. Is it maybe because of save import, or is it a bug or is it by design?

**Comment by Keranik** [comment]
It's just the vanilla behavior of storages.

It can be changed though.

**Comment by VerisZG** [comment]
Interesting, so vanilla has problems with two tier 2 belts. Can you change it maybe to beave like 0.0.3 without any constraints?
It would be even more awesome to have 6 input/output connectors as in 0.0.3.

Btw, I really appreciate your mod and your work. Now the game so much better.

**Comment by VerisZG** [comment]
Do you have patreon or something?

**Comment by VerisZG** [comment]
Oh, and is it possible to adjust unity cost for emptying the storage? Currently 128k storage uses like 127 unity to empty. I think that you could make 1/5 or 1/4 of this numer (if possible) so we can reasonably get rid of them when needed.

**Comment by Keranik** [comment]
I will see if I can remove throughput limits for Patch 74 :) Thanks for reminding me about this.

You can simulate extra I/O slots if you place a connector at the output of the machine, so that you can have 3 per output or 3 per input.  Some people didn't like the extra connectors and some did, so I'm not sure if maybe that could be a toggle option in the future, but it's a little more complicated to change that on the fly.

I will look into adjusting unity cost for emptying storages as well.

Appreciate the comments :)

**Comment by VerisZG** [comment]
6 connectors is the feature that one can use if they like it, simple as that. No one forces someone to use it. Even if 6 are available people can still just use 2. I personally find that additional feature very useful in most scenarios, especially if you are missing unity and want to quickly empty one big storage - 6 belts are useful for that.

These big storages would perfectly go with bigger trucks and greater number of trucks. Last game I played, I used COT and bigger capacity trucks had problems with smaller storages. Now with bigger storages they probably wouldn't have any issues. I am so eager to see these. :)) I love landscaping ;)

**Comment by Keranik** [comment]
![image](https://github.com/Keranik/MassiveStorageMod/assets/137360086/220112a7-0785-4707-817e-70fd699971fc)
Here is what I mean when you can add extra connections for yourself

**Comment by VerisZG** [comment]
> ![image](https://private-user-images.githubusercontent.com/137360086/326206006-220112a7-0785-4707-817e-70fd699971fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDcxMDUsIm5iZiI6MTcxNDI0NjgwNSwicGF0aCI6Ii8xMzczNjAwODYvMzI2MjA2MDA2LTIyMDExMmE3LTA3ODUtNDcwNy04MTdlLTcwZmQ2OTk5NzFmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxOTQwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWZlNDgyZDI5Zjg1MmIxZDE3Y2Q0YWJhMTg5NGZjNTFiYmFiYTZmYzVmNzNkODM3MmQyM2Q1NGRhOGYwODU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cG42zT1j-diWuc6GOv0n7l3-kmc3GbTdn1fDnbfpAD4) Here is what I mean when you can add extra connections for yourself

So neat! Didn't know about that. Yes, this would work!

Thank you so much for being so supportive.

**Comment by Keranik** [comment]
This is updated btw enjoy
